USE [master]
GO

/****** Object:  Database [Minibox]    Script Date: 31/12/2560 0:12:58 ******/
CREATE DATABASE [Minibox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Minibox_Locker', FILENAME = N'C:\DbData\Minibox\Minibox.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [MS_MasterData] 
( NAME = N'F_MasterData', FILENAME = N'C:\DbData\Minibox\F_MasterData.ndf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [MS_MasterIndex] 
( NAME = N'F_MasterIndex', FILENAME = N'C:\DbData\Minibox\F_MasterIndex.ndf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [TS_Data]  DEFAULT
( NAME = N'F_Data', FILENAME = N'C:\DbData\Minibox\F_Data.ndf' , SIZE = 23552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [TS_Index] 
( NAME = N'F_Index', FILENAME = N'C:\DbData\Minibox\F_Index.ndf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Minibox_Locker_log', FILENAME = N'C:\DbData\Minibox\Minibox_log.ldf' , SIZE = 15040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Minibox] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Minibox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Minibox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Minibox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Minibox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Minibox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Minibox] SET ARITHABORT OFF 
GO

ALTER DATABASE [Minibox] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Minibox] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Minibox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Minibox] SET CURSOR_CLOSE_ON_COMMIT ON 
GO

ALTER DATABASE [Minibox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Minibox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Minibox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Minibox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Minibox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Minibox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Minibox] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [Minibox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Minibox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Minibox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Minibox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Minibox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Minibox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Minibox] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Minibox] SET  MULTI_USER 
GO

ALTER DATABASE [Minibox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Minibox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Minibox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Minibox] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Minibox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Minibox] SET QUERY_STORE = OFF
GO

ALTER AUTHORIZATION ON DATABASE::[Minibox] TO [Autobox]
GO

USE [Minibox]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Minibox] SET  READ_WRITE 
GO


